# Generated by Django 5.2.5 on 2025-08-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='job_image',
            field=models.ImageField(blank=True, null=True, upload_to='job_images/'),
        ),
    ]
