# Generated by Django 5.2.5 on 2025-08-24 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_freelancerprofile_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='job_image',
        ),
    ]
