# Generated by Django 5.2.5 on 2025-08-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_freelancerprofile_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancerprofile',
            old_name='years_experience',
            new_name='years_of_experience',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='hourly_rate_expectation',
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freelancerprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
